### ISSUE TITLE
Not working in 1.10.2

### ISSUE THREAD

**Issue by elirnm** [IBM-Bluemix/vscode-log-output-colorizer#16]
This isn't coloring anything for me in VS Code 1.10.2, not in .log files or in the output console.

**Comment by triceam** [comment]
thanks, looking into it now.  was on travel last week...

**Comment by triceam** [comment]
Looks like the mime type is not working in VS Code version 1.10.2.  I submitted an issue with VS Code project here: https://github.com/Microsoft/vscode/issues/23680

**Comment by triceam** [comment]
I have fixed support for .log files, and will push an update soon, but waiting to hear back on the mime type issue first.

**Comment by triceam** [comment]
I pushed an update that will fix `.log` files, but it is still broken in the output panel due to a "bug" in VS Code.

**Comment by triceam** [comment]
Note: this is working in the latest insiders build: `1.11.0-insider`

**Comment by triceam** [comment]
Colorizer extension is working again now that VS Code 1.11.0 has been released by Microsoft.

**Comment by triceam** [comment]
Looks like it is broken again in VS Code 1.11.1

**Comment by triceam** [comment]
OK, i finally figured it out.  This extension is, in fact, working within the latest public VSCode.  Turns out other extensions are taking advantage of mime type for colorizing the output panel, and in doing so, it may disable the functionality of this extension.   In my case, it was the [Python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) extension that was disabling it locally for me.   So, this is no longer a bug b/c it's not a problem within this extension.    I think if we can get ANSI color support working in this extension too, then we can avoid others breaking this extension's functionality.
